### ISSUE TITLE
tiles and theme choser

### ISSUE THREAD

**Issue by ammarsj** [scotthartbti/android_frameworks_base#10]
![screenshot_2014-01-13-14-44-43](https://f.cloud.github.com/assets/5116148/1900421/bd23c678-7c51-11e3-98f1-32c23b4fec65.png)
![screenshot_2014-01-13-14-45-17](https://f.cloud.github.com/assets/5116148/1900423/cffb557c-7c51-11e3-9c4b-2a3bcffbf864.png)

hi my dear i know it wrote alot but i love the rom and want to best… i note other issue when i change my theme in theme choser the quick tiles not change with changing the theme i mean all appear as black and can play with transparent of it only… in all release for us also..this photos from other rom and the last from beanstalk rom. i hope you understand what i mean…. and sorry for my report if you dont like it i will stop to post about issue here…. thanks

**Comment by ammarsj** [comment]
what about this problem please and other new features like gesture anywhere and the new navbar style ...i found it in 2 rom only.....unlimit number of buttons and 3 action of each button .short,long and double click ........thanks in advance

**Comment by ammarsj** [comment]
![screenshot_2014-01-24-19-49-57](https://f.cloud.github.com/assets/5116148/2047010/36c1190a-8a11-11e3-976c-7b717a8eceb2.png)

i mean like this

**Comment by scotthartbti** [comment]
OK, im going to say this as nicely as possible.  This system of opening and reporting issues isnt to 'request' multiple features be added.  I have created this based on what i like and what is best for the build in my opinion.   Im going to need you to stop requesting that multiple things keep being added.  I am not doing this for you and i am not being paid.  If you want those features added so much, by all means, add them yourself.  Otherwise, switch to another build if my options are not plentiful enough for you.

**Comment by ammarsj** [comment]
Ok. I found what i need
