### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_frameworks_base#14]
I think the following should be openFileChooser instead of showFileChooser.

target Java: webviewchromium (/home/shlomy/beanstalk/out/target/common/obj/JAVA_LIBRARIES/webviewchromium_intermediates/classes)
frameworks/webview/chromium/java/com/android/webview/chromium/WebViewContentsClientAdapter.java:743: cannot find symbol
symbol  : method showFileChooser(android.webkit.ValueCallback<java.lang.String[]>,java.lang.String,boolean)
location: class android.webkit.WebChromeClient
            mWebChromeClient.showFileChooser(uploadFilePathsCallback,
                            ^
Note: Some input files use or override a deprecated API.

**Comment by scotthartbti** [comment]
Nothing has been changed that would affect that.  This is caused by 1 of 2 things.  It is either a dirty build and you need to do a make clean/make clobber or 2) this is caused by changes on the cm side of things and i havent updated my repo's in a few days.  Regardless of which one is causing the issue, I will update my repo's and push them later this evening.

**Comment by sreinst1** [comment]
It must be (2) because I checked the source file from CM and it doesn't contains this method (showFileChooser).

**Comment by scotthartbti** [comment]
It doesnt need to ... the actual part that returned the error message can
be caused from an array of things...

**Comment by sreinst1** [comment]
I don't understand what you're saying. There are two problems:
1. There is no 'showFile...' method in the class of the member on which it
is invoked.
2. The signature of 'openFile...' and the parameters to 'showFile...' do
not match.

**Comment by sreinst1** [comment]
The previous one is fixed, now I get this:
target Java: Dialer
(/home/shlomy/beanstalk/out/target/common/obj/APPS/Dialer_intermediates/classes)
packages/apps/Dialer/../InCallUI/src/com/android/incalluibind/ServiceFactory.java:21:
package com.android.dialer.omni does not exist
import com.android.dialer.omni.PhoneNumberServiceImpl;
                              ^

**Comment by scotthartbti** [comment]
Yes because i updated and pushed my repos.  You got that message because i havent pushed the dialer package yet.  Please refrain from using this reporting system for build issues such as the two previous ones.  When you see the dialer package is updated, you will just need to repo sync and will be able to build.

**Comment by scotthartbti** [comment]
FYI...  pushed the dialer package updates.  repo sync and build again and youll be fine.

**Comment by sreinst1** [comment]
Thanks. Is there somewhere else for posting build problems?
בתאריך 31 בינו 2014 18:01, "scotthartbti" notifications@github.com כתב:
